version: '3.7'

services:
  api:
    build: .
    restart: unless-stopped
    environment:
      - DB_CONN_STRING=postgres://postgres:postgres@db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"