version: '3.7'

services:
  api:
    image: obitech/go-build-tools
    working_dir: /app
    volumes:
      - ".:/app"
      - type: bind  # share host's go cache
        source: "${GOPATH}/pkg"
        target: "/build/pkg"
    restart: unless-stopped
    command: reflex -s -r "\\.(go|yaml)$$" -- go run .
    environment:
      - DB_CONN_STRING=postgres://postgres:postgres@db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"