// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID           string    `json:"id"`
	FirstName    *string   `json:"firstName"`
	LastName     *string   `json:"lastName"`
	ArtistName   *string   `json:"artistName"`
	Pronouns     []*string `json:"pronouns"`
	DateOfBirth  *string   `json:"dateOfBirth"`
	PlaceOfBirth *string   `json:"placeOfBirth"`
	Nationality  *string   `json:"nationality"`
	Language     *string   `json:"language"`
	Facebook     *string   `json:"facebook"`
	Instagram    *string   `json:"instagram"`
	BioGer       *string   `json:"bioGer"`
	BioEn        *string   `json:"bioEn"`
}

type Artwork struct {
	ID              string    `json:"id"`
	Title           *string   `json:"title"`
	ArtistID        *Artist   `json:"artistID"`
	SynopsisEn      *string   `json:"synopsisEN"`
	SynopsisDe      *string   `json:"synopsisDE"`
	Pictures        []*string `json:"pictures"`
	MaterialDemands *string   `json:"materialDemands"`
	InsuranceAmount *string   `json:"insuranceAmount"`
	SalesVal        *string   `json:"salesVal"`
	Height          *string   `json:"height"`
	Length          *string   `json:"length"`
	Width           *string   `json:"width"`
	Weight          *string   `json:"weight"`
	Category        *string   `json:"category"`
}

type ArtworkEventLocation struct {
	ArtworkID                  *Artwork  `json:"artworkID"`
	EventID                    *Event    `json:"eventID"`
	LocationID                 *Location `json:"locationID"`
	WillBeSentByPost           *bool     `json:"willBeSentByPost"`
	WillBeSentBySpedition      *bool     `json:"willBeSentBySpedition"`
	IsCollectedAfterExhibition *bool     `json:"isCollectedAfterExhibition"`
	IsBuiltOnsite              *bool     `json:"isBuiltOnsite"`
	IsBuiltByArtist            *bool     `json:"isBuiltByArtist"`
	ShippingAddress            *Location `json:"shippingAddress"`
	Packaging                  *string   `json:"packaging"`
	Material                   *string   `json:"material"`
	NoPieces                   *int      `json:"noPieces"`
	Size                       *float64  `json:"size"`
	PubAgreement               *string   `json:"pubAgreement"`
}

type Event struct {
	ID        string           `json:"id"`
	Name      *string          `json:"name"`
	StartTime *string          `json:"startTime"`
	Location  *Location        `json:"location"`
	Artists   []*InvitedArtist `json:"artists"`
}

type InvitedArtist struct {
	ArtistID       *Artist `json:"artistID"`
	EventID        *Event  `json:"eventID"`
	TravelExpenses *string `json:"travelExpenses"`
	Confirmation   *string `json:"confirmation"`
}

type Location struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Country     *string `json:"country"`
	Zip         *string `json:"zip"`
	Picture     *string `json:"picture"`
	Description *string `json:"description"`
	Lat         *string `json:"lat"`
	Lon         *string `json:"lon"`
}
