// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Artist struct {
	ID           string    `json:"id"`
	FirstName    string    `json:"firstName"`
	LastName     string    `json:"lastName"`
	ArtistName   *string   `json:"artistName"`
	Pronouns     []*string `json:"pronouns"`
	DateOfBirth  *string   `json:"dateOfBirth"`
	PlaceOfBirth *string   `json:"placeOfBirth"`
	Nationality  *string   `json:"nationality"`
	Language     *string   `json:"language"`
	Facebook     *string   `json:"facebook"`
	Instagram    *string   `json:"instagram"`
	Bandcamp     *string   `json:"bandcamp"`
	BioGer       *string   `json:"bioGer"`
	BioEn        *string   `json:"bioEn"`
	Email        *string   `json:"email"`
}

type ArtistInput struct {
	ID           *string   `json:"id"`
	FirstName    string    `json:"firstName"`
	LastName     string    `json:"lastName"`
	ArtistName   *string   `json:"artistName"`
	Pronouns     []*string `json:"pronouns"`
	DateOfBirth  *int      `json:"dateOfBirth"`
	PlaceOfBirth *string   `json:"placeOfBirth"`
	Nationality  *string   `json:"nationality"`
	Language     *string   `json:"language"`
	Facebook     *string   `json:"facebook"`
	Instagram    *string   `json:"instagram"`
	Bandcamp     *string   `json:"bandcamp"`
	BioGer       *string   `json:"bioGer"`
	BioEn        *string   `json:"bioEn"`
	Email        *string   `json:"email"`
}

type Artwork struct {
	ID              string    `json:"id"`
	Title           *string   `json:"title"`
	Artist          *Artist   `json:"artist"`
	SynopsisEn      *string   `json:"synopsisEN"`
	SynopsisDe      *string   `json:"synopsisDE"`
	Pictures        []*string `json:"pictures"`
	MaterialDemands *string   `json:"materialDemands"`
	InsuranceAmount *string   `json:"insuranceAmount"`
	SalesVal        *string   `json:"salesVal"`
	Height          *float64  `json:"height"`
	Length          *float64  `json:"length"`
	Width           *float64  `json:"width"`
	Weight          *float64  `json:"weight"`
	Category        *string   `json:"category"`
}

type ArtworkEventLocation struct {
	Artwork                    *Artwork  `json:"artwork"`
	Event                      *Event    `json:"event"`
	Location                   *Location `json:"location"`
	WillBeSentByPost           *bool     `json:"willBeSentByPost"`
	WillBeSentBySpedition      *bool     `json:"willBeSentBySpedition"`
	IsCollectedAfterExhibition *bool     `json:"isCollectedAfterExhibition"`
	IsBuiltOnsite              *bool     `json:"isBuiltOnsite"`
	IsBuiltByArtist            *bool     `json:"isBuiltByArtist"`
	ShippingAddress            *Location `json:"shippingAddress"`
	Packaging                  *string   `json:"packaging"`
	Material                   *string   `json:"material"`
	NoPieces                   *int      `json:"noPieces"`
	Size                       *float64  `json:"size"`
	PubAgreement               *string   `json:"pubAgreement"`
}

type Event struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	StartTime *int             `json:"startTime"`
	Location  *Location        `json:"location"`
	Artists   []*InvitedArtist `json:"artists"`
}

type EventInput struct {
	ID             *string               `json:"id"`
	Name           string                `json:"name"`
	StartTime      *int                  `json:"startTime"`
	LocationID     *string               `json:"locationID"`
	InvitedArtists []*InvitedArtistInput `json:"invitedArtists"`
}

type GetArtistInput struct {
	ID         *string `json:"id"`
	LastName   *string `json:"lastName"`
	ArtistName *string `json:"artistName"`
}

type GetEventInput struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type GetLocationInput struct {
	ID   *string `json:"id"`
	Name *string `json:"name"`
}

type InvitedArtist struct {
	Artist    *Artist `json:"artist"`
	Confirmed bool    `json:"confirmed"`
}

type InvitedArtistInput struct {
	ID        string `json:"id"`
	Confirmed bool   `json:"confirmed"`
}

type Location struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Country     *string `json:"country"`
	Zip         *string `json:"zip"`
	City        *string `json:"city"`
	Street      *string `json:"street"`
	Picture     *string `json:"picture"`
	Description *string `json:"description"`
	Lat         *string `json:"lat"`
	Lon         *string `json:"lon"`
}

type LocationInput struct {
	ID   *string `json:"id"`
	Name string  `json:"name"`
}
